api/pkg/controller/sessions.go, api/pkg/filestore/fs.go, api/pkg/filestore/gcs.go, docs/todo.md, frontend/src/pages/Dashboard.tsx
=> Share edit

api/pkg/system/http.go
browser and api clients will be more happy
=> fix json headers for responses 

api/pkg/controller/sessions.go, api/pkg/data/utils.go, api/pkg/server/handlers.go, api/pkg/types/types.go, frontend/src/components/session/FineTuneTextInputs.tsx, frontend/src/components/session/FineTuneTextQuestions.tsx, frontend/src/components/session/InteractionFinetune.tsx, frontend/src/pages/New.tsx
=> 131 automatic progression

api/pkg/controller/sessions.go
=> fix bug where the top level session lora_dir was not being copied

api/pkg/controller/dataprep.go, api/pkg/controller/sessions.go, api/pkg/controller/utils.go, api/pkg/system/http.go, runner/axolotl_finetune.py, unstructured/src/main.py
=> 135 no auto progress on error

api/cmd/helix/serve.go, api/pkg/server/handlers.go, api/pkg/server/server.go, api/pkg/types/types.go, docker-compose.dev.yaml, docker-compose.yaml, frontend/src/contexts/account.tsx, frontend/src/pages/Session.tsx, frontend/src/types.ts
admins can clone entire sessions and they are given the option to clone into their account or the evals account
(if the EVAL_USER_ID is not set then it won't give the option to clone into it)
=> 152 admin clone everything

api/pkg/dataprep/qapairs/qapairs.go
just tolerate some failures for now
=> together.ai json mode isn't ready for prime time yet.

Dockerfile.runner, cog/helix_cog_wrapper.py, runner/axolotl_finetune.py, runner/sdxl_finetune.py, runner/sdxl_inference.py
=> hopefully fix #176

frontend/src/components/system/NewAppbar.tsx, frontend/src/components/widgets/Window.tsx, frontend/src/contexts/theme.tsx, frontend/src/pages/New.tsx
hide docs icon
show inf/ft switch on logged out state
mobile sizing of new session message, button hover colour on inline button
randomly show 3 example prompts from 6
modal background colour on light mode fix
default to dark mode
=> various design tweaks from feedback

api/pkg/config/runner_config.go, api/pkg/model/models.go, api/pkg/server/handlers.go, api/pkg/types/models.go, frontend/src/components/system/NewAppbar.tsx
=> add missing commit

api/cmd/helix/run.go, go.mod, go.sum
used in helix-dagger module https://github.com/helixml/dagger/blob/main/main.go
=> update run command to work against remote helix api

api/cmd/helix/gptscript.go, api/pkg/config/config.go, api/pkg/server/tool_handlers.go, api/pkg/server/tool_handlers_test.go, api/pkg/testfaster_client/api.go, api/pkg/testfaster_client/get.go, api/pkg/testfaster_client/websocket.go, api/pkg/tools/informative_or_actionable_test.go, api/pkg/tools/tools.go, api/pkg/tools/tools_api_run_action.go, api/pkg/tools/tools_gptscript.go
Execute gptscript on microVMs for security. Open up gptscript support to the SaaS
=> Remote gptscript

frontend/src/components/system/NewAppbar.tsx, frontend/src/pages/New.tsx
pass bigScreen in to getToolbarElement
=> bigScreen fix

api/pkg/config/config.go, api/pkg/server/handlers.go, api/pkg/types/types.go, frontend/package.json, frontend/src/hooks/useTracking.ts, frontend/src/index.tsx, frontend/src/pages/New.tsx, frontend/src/router.tsx, frontend/yarn.lock
This adds rudderstack tracking if the env variables are provided
=> add tracking with rudder stack

api/pkg/config/runner_config.go, api/pkg/model/models.go, api/pkg/server/handlers.go, api/pkg/types/models.go, charts/helix-runner/values.yaml, frontend/src/components/system/NewAppbar.tsx, frontend/src/types.ts
Prettier didnt mess up the code this time(because i disabled it)
=> changes to add phi3 model

api/pkg/server/session_handlers.go, api/pkg/types/models.go, frontend/src/components/session/FineTuneCloneInteraction.tsx
the model name was being assigned wrong - hide the "add documents" button we need to fix this next
=> fix fine tuning

api/pkg/auth/keycloak.go
And remove conditional frontend URL setting, to always set it when starting up
=> Don't update realm config twice.

api/pkg/auth/keycloak.go, api/pkg/controller/sessions.go, api/pkg/controller/tool_actions.go, api/pkg/data/utils.go, api/pkg/runner/controller.go, api/pkg/server/app_handlers.go, api/pkg/server/openai_chat_handlers.go, api/pkg/server/server.go, api/pkg/server/session_handlers.go, api/pkg/types/types.go, frontend/src/components/create/InferenceTextField.tsx, frontend/src/components/system/Page.tsx, frontend/src/hooks/useApps.ts, frontend/src/pages/App.tsx, frontend/src/pages/Create.tsx, frontend/src/pages/Session.tsx, frontend/src/types.ts, stack
This adds checkboxes for the `shared` and `global` settings:
It also enables non github apps to be created and updates from the api
=> Assistant sessions

api/cmd/helix/runner.go, api/pkg/controller/queue.go, api/pkg/model/models.go, api/pkg/model/ollama_generic.go, api/pkg/runner/controller.go, api/pkg/server/handlers.go, api/pkg/server/server.go, api/pkg/types/models.go, api/pkg/types/openai.go, frontend/src/pages/Account.tsx
AZURE_OPENAI env vars now work and are documented
vocode should also work unmodfiied against helix now
=> Azure openai compat

api/pkg/runner/axolotl_model_instance.go, api/pkg/runner/ollama_model_instance.go
https://www.youtube.com/watch?v=Fow7iUaKrq4
=> kill ollama process _group_, not just parent process

api/pkg/runner/utils.go
Ollama seems to start its own process group, thereby flummoxing our attempts to manage subprocesses with a process group. The process tree tends to remain intact though, so we can at least manage it by hand. Adding some latency to SIGTERM followed by waiting followed by SIGKILL won't be a bad thing to handle possible race conditions with deallocating/detecting available GPU memory when switching ollama instances
=> I don't love this approach, but it seems to work in interactive testing.

api/pkg/controller/tool_actions.go
This is required to temporarily work around the limitation that Apps don't get system prompts injected into calls. This is a temporary fix and will be fixed properly with a big refactor.
=> fix(api): prepend app system prompt to all messages

api/pkg/model/models.go, api/pkg/types/models.go
through the API / app configuration
=> add support for various llama3:8b quants

api/pkg/server/handlers.go
=> fix(api): fix unmarshalling of API key

frontend/src/components/create/InferenceTextField.tsx, frontend/src/pages/Create.tsx
This is required because the current sessions/chat API is quite slow.
=> chore(ui): add waiting spinner when submitting a new request from an app

api/pkg/server/handlers.go, api/pkg/server/session_handlers.go, api/pkg/tools/informative_or_actionable.go
=> fix: text inference sessions restart using the openai controller

api/pkg/config/config.go
.. on the default inference provider (helix)
=> switch default tools model to one that exists 

docker-compose.dev.yaml, docker-compose.yaml, install.sh
Tested working:
- localhost controlplane and runner
- localhost control plane
- cli
- runner with external API host
=> fix(install): test and fix installer

api/pkg/tools/informative_or_actionable.go, api/pkg/tools/tools_api.go, api/pkg/tools/tools_api_test.go, integration-test/cli/test_jobvacancies.sh
Also, more consistent with is_actionable
=> Rearrange prepare_api_request to be more reliable 

frontend/src/pages/App.tsx
handle the case where we need to save the app for the first time when we do inference
=> save on inference

api/pkg/rag/rag_typesense.go
We queue requests while we wait
You might ask, multiple calls to ensureReady will work because closing a channel can be propogated to multiple readers right?
Yes, you're absolutely correct. Closing a channel can indeed be propagated to multiple readers, which makes the ensureReady approach work well for multiple concurrent calls. Let's break this down: Channel behavior:
When a channel is closed, any current or future reads from the channel will immediately return the zero value for the channel's type and a second boolean value of false. This behavior is consistent across all goroutines that might be reading from the channel. In our ensureReady method:
```go
func (t *Typesense) ensureReady(ctx context.Context) error {
select {
case <-t.ready:
return nil
case <-ctx.Done():
return ctx.Err() …
```
=> fix: allow typesense to boot independently of the rest of the stack

api/pkg/runner/llm_ollama_model_instance.go
recover from panic in write to closed channel when modelinstance is shut down concurrently with trying to process some work
also put back a client creation mutex that was commented out in a previous errant attempt to stop tests hanging
=> don't restart entire runner when one modelinstance is being shut down

frontend/src/contexts/streaming.tsx, frontend/src/pages/Session.tsx
=> fix(ui): reinstate fine-tuning progress in UI

docker-compose.runner.yaml, install.sh, runner/helix-llama3.2-instruct-1b-v1.yml, runner/sdxl_finetune.py, runner/sdxl_inference.py
Some of the files contained empty space characters. This PR removes them.
We also remove some variables from some finetuning scripts which are initialized but not actually used in the scripts.
Finally we gave it a small `ruff` formatting trim 💅
=> Small clean up of empty chars and unusued vars.

.dockerignore, .gitignore, Dockerfile.gptscript
Add vendor to gitignore and dockerignore.
Remove some empty space chars.
=> chore: small cleanup

api/pkg/tools/informative_or_actionable.go
This commits update the [system] prompt which lets the model decide whether the return response is actionable via tools or not.
We are explicitly telling the model to ONLY use the available tools so it doesn't make things up.
We are once again also removing some empty space chars.
=> Update actionable system prompt

go.mod, go.sum
See: https://github.com/gptscript-ai/gptscript/issues/913
Marking as draft for now.
=> Use fork of gptscript and update prompt to user

docker-compose.dev.yaml, docker-compose.yaml
* main compose file
* local dev compose file
=> Update docker-compose file so gptscript uses RUNNER_TOKEN

api/pkg/scheduler/scheduler.go, api/pkg/scheduler/scheduler_test.go
=> [WIP] refactor(scheduler): fix flakey test and refactor to make more testable

.golangci.yml, operator/go.mod, operator/go.sum
https://github.com/helixml/helix/security/dependabot/77
=> Bump gRPC module

api/pkg/controller/dataprep.go, api/pkg/controller/sessions.go, api/pkg/controller/tool_actions.go, api/pkg/server/handlers.go, api/pkg/server/session_handlers.go
This PR adds request context session plumbing. 
These propagate all the way down to the controller.
=> Add context plumbing for sessions.

api/pkg/auth/mock.go, api/pkg/cli/app/apply.go, api/pkg/cli/app/cmd.go, api/pkg/cli/app/list.go, api/pkg/cli/fs/cmd.go, api/pkg/cli/knowledge/cmd.go, api/pkg/cli/knowledge/inspect.go, api/pkg/cli/knowledge/list.go, api/pkg/cli/knowledge/remove.go, api/pkg/client/app.go, api/pkg/controller/knowledge/crawler/firecrawl.go, api/pkg/controller/knowledge/knowledge_indexer_test.go, api/pkg/controller/sessions.go, api/pkg/filestore/gcs.go, api/pkg/github/utils.go, api/pkg/openai/helix_openai_client.go, api/pkg/openai/helix_openai_server.go, api/pkg/openai/openai_client.go, api/pkg/openai/transport/transport.go, api/pkg/runner/cog_model_instance.go, api/pkg/runner/controller.go, api/pkg/runner/controller_inference.go, api/pkg/runner/controller_test.go, api/pkg/scheduler/scheduler_test.go, api/pkg/scheduler/util.go, api/pkg/server/github_handlers.go, api/pkg/server/handlers.go, api/pkg/server/session_handlers.go, api/pkg/tools/tools_gptscript.go, api/pkg/tools/tools_gptscript_test.go
This is a vol3 to the following
* https://github.com/helixml/helix/pull/655
* https://github.com/helixml/helix/pull/657
=> Revive linter fixes

api/pkg/prompts/prompts.go, api/pkg/server/server.go, api/pkg/store/migration_scripts.go, api/pkg/store/postgres.go, api/pkg/testfaster_client/api.go
See: https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#blank-imports
> Description: Blank import should be only in a main or test package, or have a comment justifying it.
=> Add comments to blank imports

.drone.yml, api/pkg/types/types.go, operator/.golangci.yml, operator/go.mod, operator/go.sum, operator/internal/controller/aiapp_controller.go, operator/test/e2e/e2e_test.go, operator/test/utils/utils.go
During helix refactoring we didnt notice that the operator has been neglected by CI hence not really tested / run through the build pipeline. We are fixing the build issues and CI setup
=> Fix operator code and add CI

api/pkg/server/app_handlers.go, frontend/src/components/app/AddKnowledgeDialog.tsx, frontend/src/components/app/GPTScriptsSection.tsx, frontend/src/hooks/useApps.ts, frontend/src/pages/App.tsx, frontend/src/pages/Apps.tsx, frontend/src/types.ts, frontend/src/utils/apps.ts
this:
* updates the app config types to reflect the `omitempty` go types
* when the "new" app button is pressed, it creates the app immediately
* it sets the name to the ID
* the name field shows as blank if the name is the ID
* this fixes various bugs where we need the ID of the app to add knowledges
* fixes some UX issues when adding a new URL based knowledge
* fixes a bug when deleted the last remaining knowledge
* fixes a bug when updating the name & desc and then add a knowledge before saving
=> 701 app creation bug

api/pkg/server/app_handlers.go, frontend/src/components/app/AddKnowledgeDialog.tsx, frontend/src/components/app/GPTScriptsSection.tsx, frontend/src/hooks/useApps.ts, frontend/src/pages/App.tsx, frontend/src/pages/Apps.tsx, frontend/src/types.ts, frontend/src/utils/apps.ts
undoing this, since it broke preview/inference for apps
Reverts helixml/helix#708
=> Revert "701 app creation bug"

api/pkg/server/app_handlers.go, frontend/src/components/app/AddKnowledgeDialog.tsx, frontend/src/components/app/GPTScriptsSection.tsx, frontend/src/hooks/useApps.ts, frontend/src/pages/App.tsx, frontend/src/pages/Apps.tsx, frontend/src/types.ts, frontend/src/utils/apps.ts
=> Revert "Revert "701 app creation bug""

install.sh
(sudo docker is often broken e.g on macOS); add timeouts too
=> don't require sudo docker in install.sh

api/pkg/server/server.go
for custom TLS connections to keycloak from api
we now support setting `SSL_CERT_FILE` or `SSL_CERT_DIR` env vars on helix controlplane (api) container/pod
=> feat(tls): support SSL_CERT_DIR in keycloak proxy

api/pkg/server/auth_middleware.go
=> Revert "Admin fix"

api/pkg/config/config.go, api/pkg/server/auth_middleware.go, api/pkg/server/auth_utils.go, api/pkg/server/handlers.go, api/pkg/server/server.go, charts/helix-controlplane/values-example.yaml, docker-compose.dev.yaml, docker-compose.yaml, scripts/kind_helm_install.sh
=> Revert "Introduce ADMIN_USER_SOURCE for checking admin users"

api/pkg/config/config.go, api/pkg/server/auth_middleware.go, api/pkg/server/auth_utils.go, api/pkg/server/handlers.go, api/pkg/server/server.go, docker-compose.dev.yaml, docker-compose.yaml, scripts/kind_helm_install.sh
This is a rehash of https://github.com/helixml/helix/pull/743 which was broken and was followed up by https://github.com/helixml/helix/pull/772
The fundamental issue was the decoding of `AdminSrcType` - which failed to decode and defaulted to `""`.
=> Admin src vol2

api/pkg/tools/informative_or_actionable.go, api/pkg/tools/tools_api.go
instead of two user messages, which vLLM barfs at, just add the hint string directly to the user's last message
=> fix: vLLM compat

api/pkg/controller/handlers.go, api/pkg/runner/controller.go, api/pkg/runner/diffusers_client.go, api/pkg/runner/gpu.go, api/pkg/runner/gpu_test.go, api/pkg/runner/ollama_runtime.go, api/pkg/runner/server.go, api/pkg/runner/slot.go, api/pkg/runner/utils_unsafe.go, api/pkg/scheduler/cache.go, api/pkg/scheduler/errors.go, api/pkg/scheduler/queue.go, api/pkg/scheduler/runner.go, api/pkg/scheduler/scheduler.go, api/pkg/scheduler/slot.go, api/pkg/server/utils.go, api/pkg/types/runner.go, api/pkg/types/types.go, scripts/k6/openai-prod.js
- Caching for dashboard endpoints
- Fixing GPU calculations
- New non-blocking queue
- Bug fixes in the runner
=> refactor(runner): new non-blocking queue and fix lots of little bugs

.drone.yml, integration-test/smoke/chat_test.go, integration-test/smoke/helper/apps.go, integration-test/smoke/helper/login.go, integration-test/smoke/helper/util.go, integration-test/smoke/inference_image_test.go, integration-test/smoke/launchpad_logs_test.go, integration-test/smoke/setup_test.go
=> test(smoke): add launchpad test that verifies chats aren't logged

charts/helix-controlplane/Chart.yaml, charts/helix-controlplane/templates/deployment.yaml, charts/helix-controlplane/templates/deployment_gptscript_runner.yaml, charts/helix-controlplane/values-example.yaml
clean up some issues with the charts
=> Chart clean up 

haystack_service/app/vectorchord/components/embedding_retriever.py, haystack_service/app/vectorchord/document_store/document_store.py
The previous implementation incorrectly assumed that vectorchord calculates cosine similarity, it doesn't is uses cosine DISTANCE.
=> fix(haystack): fix cosine similarity calculation

api/pkg/model/models.go, api/pkg/scheduler/runner.go, api/pkg/scheduler/runner_test.go
depending on the gpu the vllm models land on
=> feature: dynamically adjust --gpu-memory-utilization

api/cmd/helix/serve.go, api/pkg/scheduler/prewarming_connection_test.go, api/pkg/scheduler/prewarming_intelligent_test.go, api/pkg/scheduler/runner.go, api/pkg/scheduler/runner_test.go, api/pkg/scheduler/scheduler.go, api/pkg/scheduler/workload.go
also adjust vllm params, add tests
=> much simpler prewarming implementation
