api/cmd/helix/root.go, api/pkg/runner/controller.go, api/pkg/runner/server.go, go.mod, go.sum
=> Local server for dagger cli

api/pkg/controller/sessions.go, api/pkg/runner/controller.go, api/pkg/server/handlers.go, api/pkg/types/types.go
by giving running models a head start on claiming sessions, we avoid the case where there's, say, a base mistral already loaded into gpu memory and ready to go on runner 1, but runner 2 beats runner 1 in the race to poll for a session, then runner 2 gets it even though this introduces more latency to the user and is suboptimal because the request could have been serviced on runner 1 immediately
=> give running models a 2 second headstart to claim any session

api/pkg/controller/sessions.go, api/pkg/runner/controller.go, api/pkg/server/handlers.go, api/pkg/types/types.go
include finetuneFile as part of the rejection filter so that we don't ignore requests for _different_ finetunes than we're currently running (which we can't service)
=> fix bug where sdxl finetune is running and base sdxl inference request hangs forever

api/pkg/controller/handlers.go, api/pkg/server/handlers.go, api/pkg/server/server.go, api/pkg/store/migrations/0009_drop_balance_transfer.down.sql, api/pkg/store/migrations/0009_drop_balance_transfer.up.sql, api/pkg/store/postgres.go, api/pkg/store/types.go, api/pkg/types/types.go, frontend/src/contexts/account.tsx, frontend/src/types.ts
This removes the balance transfer code that we don't actually need any more - it uses `drop table if exists balance_transfer;` in case the table was never actually created
=> we don't need the balance transfer code any more - remove

api/pkg/controller/queue.go
=> use last interaction time rather than session creation time

frontend/src/pages/New.tsx
when user has never clicked the toggle before, make sure we highlight which mode we're currently in
before:
after:
=> highlight inference mode when it's never been clicked

.drone.yml, Dockerfile.demos, api/pkg/controller/sessions.go, api/pkg/server/handlers.go, api/pkg/server/tool_handlers.go, api/pkg/server/tool_handlers_test.go, api/pkg/store/store.go, api/pkg/store/store_tools.go, api/pkg/tools/tools_api.go, api/pkg/tools/tools_api_response.go, api/pkg/tools/validation.go, api/pkg/types/types.go, docker-compose.yaml, frontend/src/components/datagrid/Tools.tsx, frontend/src/components/widgets/StringMapEditor.tsx, frontend/src/contexts/account.tsx, frontend/src/hooks/useTools.ts, frontend/src/pages/New.tsx, frontend/src/pages/Tool.tsx, frontend/src/types.ts
This turns global tools into a flag that can be edited by admins.
Global tools will appear in the users list of tools alongside their own tools - but they will be read-only
Only admins can CRUD a global tool (but everyone can Read)
The form is disabled if the user is looking at the details of a global tool and the query params and headers are removed so we can safely show the tool details to non-admins
This also builds and runs the demo container so we can add our demos as global tools
=> 228 global tools

README.md, UPGRADING.md, update-realm-settings.sh
The helix realm setting were hardcoding localhost, which are causing trouble on new installs where custom DNS hostnames were specified for keycloak
=> Keycloak 23 import fix

api/pkg/model/axolotl_mistral7b.go, charts/helix-runner/templates/deployment.yaml, charts/helix-runner/values-example-3090.yaml, charts/helix-runner/values.yaml
mistral-7b became gated, breaking our text finetuning, allow operators to unlock it by passing their HF_TOKEN in the runner environment
=> hotfix: add passthru HF_TOKEN env var

docker-compose.yaml
Tiny change to add more stability to keycloak
=> Stop running keycloak in dev mode in production

.drone.yml, Dockerfile.runner
* high certainty large base layer that doesn't change frequently
* low certainty upper layer that we can change without burning thru hundreds of gigs of disk on our k8s clusters
=> two different model layers in docker

api/pkg/controller/sessions.go, api/pkg/controller/tool_actions.go, api/pkg/server/openai_chat_handlers.go, api/pkg/tools/tools_api.go, api/pkg/types/types.go
This PR adds the ability of OpenAI API requests to override the default API query parameters specified in a `helix.yaml` file.
To do this, first specify a query parameter in the helix.yaml. Next, in the OpenAI request, add a query parameter  that you want to override. Any key that matches a query param in `helix.yaml` will be overridden for all tools.
For example:
```
curl -XPOST -H "Authorization: Bearer hl-xxxxxxxxx" https://example.helix.ml/v1/chat/completions?page=7 --data-raw '{"model": "nop", "messages": [{"role": "user", "content": "Get some data from the api please?"}] }'
```
Will override a `helix.yaml` that has the following spec:
```
name: test
description: test app
assistants:
- name: my API
apis:
- name: Example api
description: Lists something about something
url: …
```
=> feat: add ability to override app query parameters in OpenAI API request

api/pkg/controller/handlers.go
even if they've created app keys first
=> reliably create api keys for users

api/cmd/helix/runner.go, api/pkg/config/runner_config.go, api/pkg/model/models.go, api/pkg/runner/ollama_model_instance.go, docker-compose.dev.yaml, docker-compose.runner.yaml, frontend/src/hooks/useWebsocket.ts
* Stop loading sdxl by default, neatly sidestepping the headache that was warmup models over-filling GPU memory. SDXL will still work, it just might take a bit longer on the first request to download the weights.
* Also fix bug that was stopping llama3:instruct getting loaded as a warmup model.
* Fix frontend websocket bug in development
* Make ollama keep model weights in memory forever, which is what our scheduler is designed for.
=> Fix warmups, dev websockets, ollama keepalive

charts/helix-runner/Chart.yaml, charts/helix-runner/templates/deployment.yaml, charts/helix-runner/values.yaml
- expose RUNTIME_AXOLOTL_ENABLED as per https://github.com/helixml/helix/issues/359 
- enables low cost experiments to be run by setting this to false
- this has been tested on g2-standard-8 instances with nvidia-l4 GPU in GCP for simple llama3 tests
=> feat: expose RUNTIME_AXOLOTL_ENABLED in runner chart

api/pkg/dataprep/qapairs/qapairs.go, api/pkg/tools/tools_api.go, api/pkg/tools/tools_api_test.go, api/pkg/tools/utils.go
1. factor json munging code into one place
2. add a test that covers the case we see where model includes backticks but not the word json at the start
3. make the test pass
=> handle LLM sending backticks with no "json"

.drone.yml, Dockerfile.typesense, charts/helix-controlplane/Chart.yaml, charts/helix-controlplane/values.yaml, docker-compose.dev.yaml, docker-compose.yaml, scripts/typesense-entrypoint.sh
typesense shouldn't need to download its embedding model, as this breaks corporate users
=> add dockerfile for typesense baked weights; update refs

api/pkg/rag/rag_typesense.go
when it is busy, 5 seconds to retry write requests might result in overload
=> fix: be more patient with typesense 

frontend/package.json, frontend/src/components/session/Markdown.tsx, frontend/src/pages/App.tsx, frontend/yarn.lock
sacrifice language detection in favor of making inline code blocks no longer appear as if they were non-inline
=> fix: inline code block rendering

docker-compose.dev.yaml, docker-compose.yaml
linux will still need Environment=OLLAMA_HOST=0.0.0.0 to be added to the ollama systemd unit
=> fix: make host.docker.internal work on linux

api/cmd/helix/qapairs.go, api/cmd/helix/serve.go, api/pkg/config/config.go, api/pkg/controller/controller.go, api/pkg/controller/inference_test.go, api/pkg/controller/queue.go, api/pkg/controller/sessions.go, api/pkg/openai/helix_openai_client.go, api/pkg/openai/helix_openai_client_test.go, api/pkg/openai/helix_openai_server.go, api/pkg/scheduler/allocator.go, api/pkg/scheduler/cluster.go, api/pkg/scheduler/errors.go, api/pkg/scheduler/placement.go, api/pkg/scheduler/scheduler.go, api/pkg/scheduler/scheduler_test.go, api/pkg/scheduler/slot.go, api/pkg/scheduler/util.go, api/pkg/scheduler/workload.go, api/pkg/server/openai_chat_handlers_test.go, api/pkg/server/runner_handlers.go, api/pkg/server/server.go, docker-compose.dev.yaml, scripts/k6/openai.js
A big refactor of the scheduler to move scheduling logic into the controller. Now, nearly all information from the runner is ignored. The only two things that are respected are:
1. The total memory set on the CLI
2. The models that are actually running.
Everything else is controlled by the control plane. Some design decisions:
- This doesn't change anything on the runner side, yet. The runners still poll and do what they do. They are still responsible for killing models when over-scheduling.
- This doesn't change anything under the current "queues". There's two queues, one for runners and one for sessions. They still exist and all the code that says "todo remove" is still there. Ideally I want to move the queues into the scheduler. Future task.
- runners and segmented by a new concept …
=> refactor(scheduler): big improvements to the scheduler to better place work

api/pkg/prompts/templates/knowledge.tmpl, api/pkg/server/openai_chat_handlers.go, api/pkg/server/session_handlers.go, api/pkg/server/session_legacy_handlers.go, api/pkg/server/utils.go, frontend/index.html, frontend/src/components/app/PreviewPanel.tsx, frontend/src/components/create/ModelPicker.tsx, frontend/src/components/session/InteractionLiveStream.tsx, frontend/src/components/session/Markdown.tsx, frontend/src/contexts/all.tsx, frontend/src/contexts/streaming.tsx, frontend/src/hooks/useCreateInputs.ts, frontend/src/hooks/useLiveInteraction.ts, frontend/src/hooks/useWebsocket.ts, frontend/src/pages/App.tsx, frontend/src/pages/Create.tsx, frontend/src/pages/Session.tsx
* Fix missing first part of messages by switching to OpenAI style SSE API
* Fix switching between different sessions while data is streaming
* Drive-by improvements to RAG prompts for more accurate citations
* Bring back the cute little flashing yellow cursor
* Fix flushing in the OpenAI API endpoints to make them much more responsive (should fix the embed too)
* Spinner while waiting for first response from sessions endpoint
* Search immediately when switching the knowledge search toggle on app editor
* Add line breaks to LLM responses that have single linebreaks
* Fix missing model spec for new apps
* Clear text box immediately on submission
=> Revamp frontend text inference, improve RAG

api/pkg/rag/rag_typesense.go
So we don't wait 2x longer than needed because of exponential backoff
=> typesense: Also bound the maximum delay to 10 seconds

frontend/src/components/widgets/FileUpload.tsx
You can also directly upload a sharegpt-style jsonl file to train on directly. But it MUST be called `finetune_dataset.jsonl` and it must have the following format:
```jsonl
{"conversations":[{"from":"human","value":"test test"},{"from":"gpt","value":"yes this is a test"}]}
{"conversations": ...
```
=> fix(ui): allow uploads of jsonl files

api/pkg/runner/controller.go, api/pkg/runner/llm_ollama_model_instance.go
since controlplane stops overscheduling now, we don't need this, and we also need to be able to reliably evict stale models
=> make eviction more reliable

api/pkg/runner/llm_ollama_model_instance.go
* to avoid falling down a crack and having requests hang forever
* belt and braces also timeout inference requests after 600 seconds, inference should never take >10 minutes
=> check ollama is ready before sending it a request

frontend/src/components/app/AppSettings.tsx, frontend/src/pages/App.tsx
This makes two changes:
1. Never disable the shared/global checkboxes.
2. Check if the app is a github app, if it is, only update the shared and global settings.
=> fix(ui): allow users to update github apps to be global/shared

charts/helix-controlplane/Chart.yaml, charts/helix-controlplane/templates/deployment.yaml, charts/helix-controlplane/values.yaml
fix issue on redirect from clicking on links in the filestore going to the internal 8844 port
=> fix: tell helm the correct url for a localhost port-forward

charts/helix-controlplane/templates/deployment_gptscript_runner.yaml, charts/helix-controlplane/values-example.yaml, charts/helix-controlplane/values.yaml, docker-compose.yaml
This adds a new service, `gptscript_runner`, to the Helix stack. It is aimed to make the `gptscript` talking to locally run LLM models via OpenAI compatible API provided by helix API service. The Helix API key required by `gptscript` to communicate with Helix must be specified via the `HELIX_API_KEY` env var: you can make it available via the .env file.
=> Add gptscript_runner service to helix stack

api/pkg/runner/llm_ollama_model_instance.go
Just for the operator's sanity, it'd be great to tell the streaming errors apart from the regular API errors dealing with tool calling.
=> Small error updates

.drone.yml, Dockerfile.lint, local-development.md, stack
We've added golangci-linter config into our codebase and now it's time to add the linter step into CI so we guarantee at least some quality of the code, such as uncompromisingly rejecting the code that does not handler errors, properly, etc.
We are also adding `Dockerfile.lint` Dockerfile for local development if you prefer that.
=> Add linter step into CI

.drone.yml, .gitignore, api/pkg/openai/context.go, api/pkg/server/auth_middleware.go, api/pkg/server/auth_utils.go, api/pkg/server/openai_chat_handlers.go, api/pkg/server/openai_chat_handlers_test.go, api/pkg/server/session_handlers.go, api/pkg/store/store_test.go, api/pkg/tools/informative_or_actionable.go, api/pkg/tools/tools_api.go, api/pkg/tools/tools_api_response.go, api/pkg/types/enums.go
We've modified the authorization check to allow runners to do chat completions. This will make integrating different types of runners eeasier at the cost of slight "security" tradeoff which we've accepted for the time being.
=> Allow RUNNER_TOKEN to perform chat completions

.golangci.yml, api/cmd/helix/runner.go, api/pkg/apps/github.go, api/pkg/github/client.go, api/pkg/github/utils.go, api/pkg/gptscript/runner.go, api/pkg/model/axolotl_mistral7b.go, api/pkg/model/cog_sdxl.go, api/pkg/model/utils.go, api/pkg/runner/controller.go, api/pkg/runner/files.go, api/pkg/runner/utils.go, api/pkg/server/app_handlers.go, api/pkg/server/github_handlers.go, api/pkg/system/http.go, api/pkg/testfaster_client/api.go, api/pkg/testfaster_client/get.go, api/pkg/types/knowledge.go, api/pkg/types/types.go, api/pkg/util/copydir/copy_dir.go
This commit is a first batch of revive linter
(https://golangci-lint.run/usage/linters/#revive) warnings that actually attempts to make Go code follow Go idioms and best practices:
* be consistent with receiver names! Dont just pick one for one method, and then a different name for another method - it creates confusion
* do not name variables such that the beginning of their name is the same as the name of the package i.e. no var in github package should start with GitHub - it stutters and frankly makes no sense.
* do not put `"."` at the end of errors you return; same with `"\"`
* avoid redundant `else` statements when all the `else` clause does is a `return` Just return!
Some unused code has been removed, too.
I'm also bumping the linter timeout.
=> Make Go code Go code again: revive linter checks

operator/go.mod, operator/go.sum
Same as https://github.com/helixml/helix/pull/658
=> (security): Bump golang.org/x/net module (CVE-2024-45338)

api/cmd/helix/test.go, api/pkg/cli/app/apply.go, api/pkg/cli/app/cmd.go, api/pkg/cli/app/inspect.go, api/pkg/cli/app/list.go, api/pkg/cli/app/remove.go, api/pkg/cli/knowledge/cmd.go, api/pkg/cli/knowledge/inspect.go, api/pkg/cli/knowledge/list.go, api/pkg/cli/knowledge/remove.go, api/pkg/cli/knowledge/versions_list.go, api/pkg/cli/secret/create.go, api/pkg/cli/secret/delete.go, api/pkg/cli/secret/list.go, api/pkg/cli/secret/update.go, api/pkg/client/app.go, api/pkg/client/client.go, api/pkg/client/fs.go, api/pkg/client/knowledge.go, api/pkg/client/secret.go
This PR refactors helix API and implements proper `context` plumbing.
The API client methods now accept `context` which is passed down to it from a callsite.
In some helix commands we do this e.g. https://github.com/helixml/helix/blob/790bc12e6a4b01f60d9a29ab6b13f805c1f1b506/api/pkg/cli/fs/remove.go#L32
But in others we dont. This is a terrible inconsistency that might prevent adding some functionality in the future (say, cli canellations, etc.)
We're now also passing context to `makeRequest` which then wraps it in the request timeout.
=> (refactor): Client context plumbing

.golangci.yml, api/pkg/scheduler/allocator.go, api/pkg/scheduler/cluster.go, api/pkg/scheduler/scheduler.go
See: https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
As an aside we really should make sure we always return exported types. UNexported are really terrible to work with: you can not switch type/type assert them - this is good for things like if we are very anal about interface breakage, but in the grand scheme of things it makes dealing with some code pretty painful at times.
=> Last revive fixes

local-development.md
There is no need for manually maintaining at TOC. GitHub has a built-in native TOC support for markdown: https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/
=> Remove TOC from local-dev README

integration-test/smoke/app_integration_test.go, integration-test/smoke/app_knowledge_test.go, integration-test/smoke/chat_test.go, integration-test/smoke/helix_cli_apply_test.go, integration-test/smoke/helix_cli_test.go, integration-test/smoke/helper/util.go, integration-test/smoke/inference_image_test.go
Rely on the global go test -timeout instead. Because in reality if one times out, then the whole test is a failure. So I only really need one timeout. And I think that 120s might sometimes be too low.
=> refactor(smoke): remove individual test timeouts

api/pkg/config/config.go, api/pkg/server/auth_middleware.go, api/pkg/server/auth_utils.go, api/pkg/server/handlers.go, api/pkg/server/server.go, charts/helix-controlplane/values-example.yaml, docker-compose.dev.yaml, docker-compose.yaml, scripts/kind_helm_install.sh
> [!IMPORTANT]
> `admin` claims in the JWT token assume `admin` boolean key **TBD**
The new `ADMIN_USER_SOURCE` env var allows to specify the source of the admin user check.
There are currently two possible admin user sources:
* `env`: admin user IDs are read from the `ADMIN_USER_IDS` env var
* `jwt`: admin JWT token claim is checked
By default, the "env" source is set. If the "jwt" source is required it must be
explicitly overridden by setting ADMIN_USER_SOURCE env var accordingly.
There was a lot of code duplication throughout so we've done a bit of boyscouting:
* auth middleware groups config in a dedicated config field
* remove the `development` field - there is no need for it (the check is
being done inside the for loop
* introduced account type which helps with dealing with …
=> Introduce ADMIN_USER_SOURCE for checking admin users

api/pkg/config/config.go
so it's not necessary to specify it in the .env
=> default admin source to env

api/pkg/server/auth_utils.go, api/pkg/server/openai_chat_handlers.go, api/pkg/server/openai_chat_handlers_test.go, api/pkg/server/websocket_server_gptscript_runner.go, api/pkg/system/uuid.go
You can now filter by the id returned by the OpenAI compatible API on apps in the LLM calls dashboard, to ease debugging.
=> OpenAI-compat API: return response IDs and log them as session IDs

frontend/src/pages/App.tsx, frontend/src/pages/Layout.tsx
When adding knowledge sources to an app, the unsaved sources would disappear from the UI after the backend polling cycle ran (every 2 seconds), before the user had a chance to save them.
The app initialization code was overwriting local knowledgeSources state with backend data whenever apps.data refreshed, causing unsaved changes to be lost.
Restructured app initialization into three separate effects with clear responsibilities:
1. App ID change effect: Resets initialization flags
2. App data loading effect: Only sets knowledge sources during initial load
3. New app initialization effect: Handles "new" app case separately
Modified the app data loading effect to only initialize knowledge sources once per app ID, while still updating the app state when backend data changes.
=> fix: smallest possible change to fix knowledge disappearing issue.

api/pkg/controller/dataprep.go, api/pkg/controller/inference.go, api/pkg/controller/knowledge/knowledge_indexer.go, api/pkg/controller/knowledge/query/query.go, api/pkg/rag/rag_haystack.go, api/pkg/server/knowledge_search_handlers.go, api/pkg/server/openai_chat_handlers_test.go, api/pkg/types/types.go, docker-compose.dev.yaml, frontend/src/components/app/AddKnowledgeDialog.tsx, frontend/src/components/app/KnowledgeSourceInputs.tsx, frontend/src/types.ts, haystack_service/app/api.py, haystack_service/app/config.py, haystack_service/app/converters.py, haystack_service/app/service.py, haystack_service/app/service_image.py, haystack_service/app/splitters.py, haystack_service/app/vectorchord/document_store/document_store.py
Introducing a new way to do RAG with vision models. New features include:
- a new haystack vision embedding pipeline to embed and store images of PDFs
- addition to the App UI to enable vision mode
- improved haystack codebase, reduced tech tebt
- tested with openai and vllm
As usual, expect some rough edges, this is cutting edge. Better documentation and improve resilience to follow.
=> feat(haystack): vision RAG pipeline

.drone.yml, Dockerfile.runner, api/pkg/openai/helix_openai_client.go, docker-compose.dev.yaml, stack
* as well as providing a new FORCE_CPU option for testing CPU vLLM on dev nodes that do have a GPU
* and bumping the base image to one with the correct version of go installed (to stop errors in development)
=> enable helix models by default

api/cmd/helix/serve.go, api/pkg/config/config.go, api/pkg/store/dynamic_providers.go, api/pkg/store/dynamic_providers_test.go, docker-compose.dev.yaml, docker-compose.yaml, install.sh
support --dynamic-providers and DYNAMIC_PROVIDERS env var (and --embeddings-provider) to seed inference providers in the db via env var
this is so that i can configure the launchpad trial vms to use relaxAI as the embeddings provider since they now helpfully support our vision embedding model in their vllm cluster
=> dynamic providers env

api/pkg/scheduler/gpu_allocation_distribution_test.go, api/pkg/scheduler/memory_calculation_inconsistency_test.go, api/pkg/scheduler/overscheduling_prevention_test.go, api/pkg/scheduler/prewarming_intelligent_test.go, api/pkg/scheduler/runner.go, api/pkg/scheduler/scheduler.go, api/pkg/scheduler/tensor_parallelism_test.go
fixed major consistency bugs where scheduler memory calculations and scheduling decisions were using different sources of truth, leading to potential over-scheduling. now everything uses local state for the hot path and explicit error handling everywhere.
- use local state (s.slots) for all memory calculations instead of mixing local/remote state  
- make getModelMemory() and calculateAllocatedMemoryPerGPU() return errors instead of silently failing with 0
- fix analyzeGlobalModelDistribution() to use same local state as scheduling decisions
- add comprehensive state source documentation explaining when to use local vs remote state
- all tests updated to handle new error returns and still pass
=> fix scheduler state consistency and eliminate silent failures
